#!/usr/bin/env python3
import argparse as arg
from numpy.random import randint
from numpy import savetxt

test_point_dir = './tests/'
parser = arg.ArgumentParser(
        description="Generate a point cloud to compute a convex hull from"
        )

parser.add_argument('filename', type=str, nargs=1,
        metavar="file",
        help="the name of the file inside of {} that contains a point cloud."
        .format(test_point_dir))

parser.add_argument('-n', '--number', type=int, nargs=1, metavar="N",
        help="the number of points to be generated in the cloud.",
        default=100)

args = parser.parse_args()

num_points = args.number[0]
filename = args.filename[0]

cloud = randint(0, high=100, size=(num_points,2), dtype=int)
savetxt(test_point_dir + filename, cloud, delimiter=',', fmt='%d')
